# Docker-compose for Graylog
version: '3'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15673:15672"
      - "5673:5672"
    labels:
      NAME: "rabbitmq"
    volumes:
      - "./docker/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins"
      #- "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro"
      #- "./autocluster-0.4.1.ez:/usr/lib/rabbitmq/lib/rabbitmq_server-3.5.5/plugins/autocluster-0.4.1.ez"
    networks:
      - template-network

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "testedb"
    #ports:
      #- "3306:3306"
    volumes:
      - ./mysql-persistence:/var/lib/mysql
    networks:
      - template-network
  
  springboot:
    build:
      context: .
    depends_on:
      - mysql
      - rabbitmq
    ports: 
      - 8089:8089
    networks:
      - template-network
    

networks: 
  template-network:
    driver: bridge